apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ template "instapy.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: {{ template "instapy.fullname" . }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ template "instapy.name" . }}
        command: ["./wait-for", "selenium-selenium-hub:4444", "--", "python", "docker_quickstart.py"]
        env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key | upper | replace "." "_" }}
            value: {{ $value | quote }}
          {{- end }}
          - name: USERNAME
            value: "jambo_hakuna_matata"
        volumeMounts:
        {{- range $secret := .Values.secrets }}
          {{- if $secret.mountPath }}
            {{- range $key := $secret.keys }}
          - name: {{ $secret.name }}
            mountPath: {{ $secret.mountPath }}/{{ $key }}
            subPath: {{ $key }}
            readOnly: true
            {{- end }}
          {{- end }}
        {{- end }}
        resources: {}
      volumes:
        {{- range .Values.secrets }}
        - name: {{ .name }}
          secret:
            secretName: {{ .name }}
        {{- end }}
      restartPolicy: Always
status: {}
