apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "instapy.fullname" . }}-run-configmap
  labels:
    app: {{ template "instapy.name" . }}
    chart: {{ template "instapy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  docker_quickstart.py: |-
{{ include (print $.Template.BasePath "/_run.txt") . | indent 4 }}
